# copied and adapted from https://github.com/clickingbuttons/lz4/blob/master/.github/workflows/publish_docs.yml
name: Docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          sudo apt update -qq
          sudo apt install -yqq binutils-dev
          zig build docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'zig-out/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
